#Application info
spring.application.name=invoice-service
server.port=8082

#Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/invoice_service_db
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#JWT secret
jwt.secret=this-is-a-very-secure-secret-key-1234567890